wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713269101.0
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 105
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 105
      3:
      - 23
      4: 3.10.13
      5: 0.16.5
      6: 4.19.2
      8:
      - 5
      13: linux-x86_64
